id: I7DFB7C9D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T23:23:34+00:00'
last_modified: '2022-06-08T12:46:59.191379+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15077
  title: སྐད་གཉིས་ཤན་སྦྱར་རབ་གསལ་ནོར་བུའི་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BF73:
      image_group_id: I1KG15386
      title: Volume 1 of skad gnyis shan sbyar rab gsal nor bu'i me long /
      total_pages: 594
      order: 1
      base_file: BF73.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
