id: P006944
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:32:08.064202
source_metadata:
  id: bdr:W1KG15077
  title: སྐད་གཉིས་ཤན་སྦྱར་རབ་གསལ་ནོར་བུའི་མེ་ལོང་།
  author: ''
  volumes:
    c9c14a7f5fae46d584ca31ac6285df2b:
      image_group_id: I1KG15386
      title: Volume 1 of skad gnyis shan sbyar rab gsal nor bu'i me long /
      volume_number: 1
      total_pages: 594
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
