id: P006944
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15077
  title: སྐད་གཉིས་ཤན་སྦྱར་རབ་གསལ་ནོར་བུའི་མེ་ལོང་།
  author: ''
  volumes:
    5e47e0c9931044fc9851e5500c129d9c:
      image_group_id: I1KG15386
      title: ''
      volume_number: 1
      total_pages: 594
ebook_metadata:
  title: སྐད་གཉིས་ཤན་སྦྱར་རབ་གསལ་ནོར་བུའི་མེ་ལོང་།
  author: ''
  sku: P006944
  cover: cover.jpg
  layers:
  - pagination
