id: P006944
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15077
  title: སྐད་གཉིས་ཤན་སྦྱར་རབ་གསལ་ནོར་བུའི་མེ་ལོང་།
  author: ''
  volumes:
    c9c14a7f5fae46d584ca31ac6285df2b:
      image_group_id: I1KG15386
      title: Volume 1 of skad gnyis shan sbyar rab gsal nor bu'i me long /
      volume_number: 1
      total_pages: 594
      base_file: v001.txt
ebook_metadata:
  title: སྐད་གཉིས་ཤན་སྦྱར་རབ་གསལ་ནོར་བུའི་མེ་ལོང་།
  author: ''
  sku: P006944
  cover: cover.jpg
  layers:
  - pagination
